### ISSUE TITLE
this.rtcEngine.videoSourceJoin(token, ...) 传入token屏幕分享无反应

### ISSUE THREAD

**Issue by lipten** [AgoraIO-Usecase/eEducation-with-Electron#24]
已经在声网控制台开启app Certificate

传入从接口生成好的channel和uid对应的token:
```
token = '0069exxxxx'
uid = 12345
channel = 'class1'
console.log(this.rtcEngine.videoSourceJoin(token, channel , info, uid));
```
videoSourceJoin返回0，

但下面这个成功的回调没有执行，userjoined 回调也没有执行，屏幕分享也没有起作用。
```
this.rtcEngine.once('videosourcejoinedsuccess', uid => {
        // clearTimeout(timer)
        console.log('success')
        this.sharingPrepared = true
        resolve(uid)
});
```

我用同样的传入方式调用 this.rtcEngine.joinChannels 是有起作用的。

**Comment by lipten** [comment]
> @lipten 你计算videosource token使用的uid是12345吗？是的话，计算token时给的权限是什么？

uid写死的测试用的，token没有设置权限，应该是默认所有权限的吧

**Comment by lipten** [comment]
> @lipten 你计算videosource token使用的uid是12345吗？是的话，计算token时给的权限是什么？

设置了权限也不行😰

token传null也不行😰

这个videoSourceJoin方法没有一个错误回调返回具体错误信息的地方吗😂

**Comment by lipten** [comment]
@plutoless 是不是这个videoSourceJoin有别于joinChannels特别的配置啊？
joinChannels调用摄像头直播就可以。

**Comment by plutoless** [comment]
@lipten videosource相当于是另一个sdk实例，所以需要确保以下事项，
1. videosourceJoin的uid和摄像头join的uid要确保不同
2. 计算token的时候其中一个参数就是uid，确保videosourcejoin调用的时候使用的uid和计算videosourcejoin的token的uid一致
3. 计算token的时候有一些权限设置，确保只添加一个join的权限，其他权利比如publish或者设置attendee role这些都是不需要的

**Comment by lipten** [comment]
@plutoless 
1. videosourceJoin的uid是54321，join的uid是12345
2. videosourcejoin的token是匹配54321的，join的token也是匹配12345的(不然join也不会有效)
3. 后端生成token代码是这样的：
```
SimpleTokenBuilder token = new SimpleTokenBuilder(appId, appCertificate, channelName, uid);
token.initPrivileges(SimpleTokenBuilder.Role.Role_Attendee);
token.setPrivilege(AccessToken.Privileges.kJoinChannel, expireTimestamp);
token.setPrivilege(AccessToken.Privileges.kPublishAudioStream, expireTimestamp);
token.setPrivilege(AccessToken.Privileges.kPublishVideoStream, expireTimestamp);
token.setPrivilege(AccessToken.Privileges.kPublishDataStream, expireTimestamp);

String result = token.buildToken();
System.out.println(result);
```

**Comment by plutoless** [comment]
把后台代码修改成这样，

SimpleTokenBuilder token = new SimpleTokenBuilder(appId, appCertificate, channelName, uid);
token.setPrivilege(AccessToken.Privileges.kJoinChannel, expireTimestamp);

String result = token.buildToken();
System.out.println(result);

@lipten

**Comment by lipten** [comment]
@plutoless 这个也不行，而ios端屏幕共享则可以，我后来用php和nodejs生成的token都可以呢。
所以总结一下情况就是：java生成的token在electron屏幕共享不生效，ios端生效，而其他语言生成的token都能生效。

**Comment by plutoless** [comment]
php和nodejs生成的token的代码贴一下

**Comment by plutoless** [comment]
@lipten  我们昨天有同事正好碰到一样的问题，用Java的代码确保只添加join的权限算的token是可以用的，你这边要不再检查一下？

**Comment by lipten** [comment]
对，去掉一些多余的权限就可以了
