### ISSUE TITLE
打包后的安装程序在windows安装的目录怎么修改？

### ISSUE THREAD

**Issue by lipten** [AgoraIO-Usecase/eEducation-with-Electron#27]
打包后的win安装程序自动装到c盘的`\Users\xxx\AppData\Local\Programs\agora-education-demo`，请问可以在安装时自定选择安装目录或者在代码里把`agora-education-demo`改成别的可以吗？

**Comment by menthays** [comment]
请参考 [electron-builder文档](https://www.electron.build)
